2022-12-03 02:18:58,629 [ZeusDataLoader(train)] Distributed data parallel: OFF
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "/workspace/zeus/examples/cifar100/train_lr.py", line 256, in <module>
    main(parse_args())
  File "/workspace/zeus/examples/cifar100/train_lr.py", line 120, in main
    train_loader = ZeusDataLoader(
  File "/workspace/zeus/zeus/run/dataloader.py", line 433, in __init__
    pynvml.nvmlInit()
  File "/root/.local/miniconda3/lib/python3.9/site-packages/pynvml/nvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/root/.local/miniconda3/lib/python3.9/site-packages/pynvml/nvml.py", line 1440, in nvmlInitWithFlags
    _nvmlCheckReturn(ret)
  File "/root/.local/miniconda3/lib/python3.9/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Unknown: Unknown Error
